<div class="art_list">
    <li><a href="Arts.php">Andreas Emeius</a>
        <a href="Arts1.php">David Hockney</a>
        <a href="Arts2.php">David Lehmann</a>
        <a href="Arts3.php">Eva Armisen</a>
        <a href="Arts4.php">Jeff Koons</a>
        <a href="Arts5.php">Kaws</a>
        <a href="Arts6.php">Kusama Yaoi</a>
        <a href="Arts7.php">Pablo Picasso</a>
        <a href="Arts8.php">Ramine</a>
        <a href="Arts9.php">Roland ST. Hubert</a>
        <a href="Arts10.php">Si on</a>
        <a href="Arts11.php">Yoshitomo Nara</a>
        <a href="Arts12.php">강건호</a>
        <a href="Arts13.php">권옥연</a>
        <a href="Arts14.php">권용택</a>
        <a href="Arts15.php">권혜조</a>
        <a href="Arts16.php">김규진</a>
        <a href="Arts17.php">김기창</a>
        <a href="Arts18.php">김남표</a>
        <a href="Arts19.php">김덕용</a>
        <a href="Arts20.php">김두선</a>
        <a href="Arts21.php">김상철</a>
        <a href="Arts22.php">김열</a>
        <a href="Arts23.php">김원근</a>
        <a href="Arts24.php">김은호</a>
        <a href="Arts25.php">김인화</a>
        <a href="Arts26.php">김종학</a>
        <a href="Arts27.php">김준</a>
        <a href="Arts28.php">김진아</a>
        <a href="Arts29.php">김창열</a>
        <a href="Arts30.php">김충현</a>
        <a href="Arts31.php">김태현</a>
        <a href="Arts32.php">김태호</a>
        <a href="#">김학두</a>
        <a href="#">김현식</a>
        <a href="#">김환기</a>
        <a href="#">나윤찬</a>
        <a href="#">노학봉</a>
        <a href="#">도성욱</a>
        <a href="#">문순우</a>
        <a href="#">문홍규</a>
        <a href="#">박서보</a>
        <a href="#">박수근</a>
        <a href="#">박영복</a>
        <a href="#">박영학</a>
        <a href="#">박영효</a>
        <a href="#">박인숙</a>
        <a href="#">백범영</a>
        <a href="#">백승수</a>
        <a href="#">변웅필</a>
        <a href="#">서세옥</a>
        <a href="#">서수영</a>
        <a href="#">손동준</a>
        <a href="#">송은주</a>
        <a href="#">신빛</a>
        <a href="#">신종섭</a>
        <a href="#">신종식</a>
        <a href="#">신창용</a>
        <a href="#">양원종</a>
        <a href="#">양태석</a>
        <a href="#">오승우</a>
        <a href="#">오윤</a>
        <a href="#">윤수영</a>
        <a href="#">윤종구</a>
        <a href="#">이강소</a>
        <a href="#">이달재</a>
        <a href="#">이대원</a>
        <a href="#">이동재</a>
        <a href="#">이두식</a>
        <a href="#">이상학</a>
        <a href="#">이선열</a>
        <a href="#">이선주</a>
        <a href="#">이영희</a>
        <a href="#">이왈종</a>
        <a href="#">이우환</a>
        <a href="#">이인섭</a>
        <a href="#">장우성</a>
        <a href="#">장희정</a>
        <a href="#">전광영</a>
        <a href="#">전뢰진</a>
        <a href="#">정규석</a>
        <a href="#">정미조</a>
        <a href="#">정술원</a>
        <a href="#">정의부</a>
        <a href="#">정판균</a>
        <a href="#">조순호</a>
        <a href="#">천경자</a>
        <a href="#">최광선</a>
        <a href="#">최영란</a>
        <a href="#">최영림</a>
        <a href="#">최한동</a>
        <a href="#">한풍렬</a>
        <a href="#">한홍수</a>
        <a href="#">허건</a>
        <a href="#">허진</a>
        <a href="#">홍순주</a>
        <a href="#">홍일화</a>
    </li>
</div>